name: scraper portal abierto
on:
 push:
   branches:
      - main
      
 schedule:
  - cron : 0 14 * * * 

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with: 
          use-public-rspm: true

      - name: run-script
        run: Rscript datos_abiertos/00_get_data.R
        
      - name: commit files
        run: |
          today=$(date +"%Y-%m-%d")
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add datos_abiertos/data/*
          git commit -m "updated datasets ${today}" -a
